import AdminWrapper from "@/components/AdminWrapper/AdminWrapper";
import Fonts from "@/components/Fonts/Fonts"; // Ensure the path is correct
import '../globals.scss'
import './Admin.scss'

export const metadata = {
  title: "Parcel Pro Connect",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Fonts />
        <AdminWrapper>
          {children}
        </AdminWrapper>
      </body>
    </html>
  );
}
