import AdminWrapper from "@/Components/AdminWrapper/AdminWrapper";
import Fonts from "@/Components/Fonts/Fonts"; // Ensure the path is correct
import '../(home)/globals.scss'

export const metadata = {
  title: "Parcel Pro Connect",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Fonts />
        <AdminWrapper>
          {children}
        </AdminWrapper>
      </body>
    </html>
  );
}
